export interface AgentConfig {
  systemInstruction: string;
  model: string;
}

export class BaseAgent {
  protected config: AgentConfig;

  constructor(config: AgentConfig) {
    this.config = config;
  }

  async run(prompt: string) {
    try {
      // 1. Point directly to your local offline brain
      const response = await fetch("http://localhost:11434/api/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: this.config.model,
          prompt: prompt,
          system: this.config.systemInstruction,
          stream: false, // Ollama will wait and send the whole message at once
        }),
      });

      if (!response.ok) {
        throw new Error(`Ollama connection failed with status: ${response.status}`);
      }

      const data = await response.json();
      return data.response; // This is the actual text generated by your local GPU/CPU
      
    } catch (error) {
      console.error(`${this.constructor.name} error:`, error);
      throw error; // If Ollama is closed, this kicks it down to your fallback
    }
  }
}

export class EdgeEducator extends BaseAgent {
  constructor() {
    super({
      model: "phi3", // 2. Swapped Gemini for the model you just downloaded!
      systemInstruction: `You are the NexusEdu Edge Educator, an offline AI tutor for students in developing regions.
            Your goal is NOT to give direct answers. You must use the Socratic method.
            
            Respond with a guiding question or a highly relatable, localized analogy to help the student figure it out themselves.`
    });
  }

  async tutor(subject: string, topic: string, studentQuery: string) {
    const prompt = `Student context: (Subject: ${subject}, Topic: ${topic})
    Student Question: "${studentQuery}"
    
    Respond as a Socratic tutor using guiding questions or analogies.`;
    
    try {
      return await this.run(prompt);
    } catch (error) {
      console.warn("Edge Educator AI failed, using fallback mock response.");
      return "Socratic Tutor Mode: Let's dive into that! But before I just give you the answer, how would you break this topic down into smaller, logical steps?";
    }
  }
}
